# Generated by Django 4.2.2 on 2023-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois_du_temps',
            fields=[
                ('Num_Emplois', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Semaine_Emplois', models.CharField(max_length=255)),
                ('Jour_Emplois', models.CharField(max_length=30)),
                ('Promotion_Emplois', models.CharField(max_length=255)),
                ('Matière_Emplois', models.CharField(max_length=255)),
                ('Nom_professeur_Emplois', models.CharField(max_length=255)),
                ('Heure_début_Emplois', models.TimeField()),
                ('Heure_fin_Emplois', models.TimeField()),
                ('Horaire_Matière_Emplois', models.PositiveIntegerField()),
                ('Temps_restant_Matière_Emplois', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Emplois du Temps',
                'verbose_name_plural': 'Emplois du Temps',
            },
        ),
    ]
