# Generated by Django 4.2.2 on 2023-06-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_emplois_du_temps_num_groupe_emplois_du_temps_salle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplois_du_temps',
            old_name='Horaire_Matière_Emplois',
            new_name='Horaire',
        ),
        migrations.RenameField(
            model_name='emplois_du_temps',
            old_name='Matière_Emplois',
            new_name='Matière',
        ),
        migrations.RenameField(
            model_name='emplois_du_temps',
            old_name='Temps_restant_Matière_Emplois',
            new_name='Temps',
        ),
        migrations.RenameField(
            model_name='emplois_du_temps',
            old_name='Heure_début_Emplois',
            new_name='début',
        ),
        migrations.RenameField(
            model_name='emplois_du_temps',
            old_name='Heure_fin_Emplois',
            new_name='fin',
        ),
        migrations.RemoveField(
            model_name='emplois_du_temps',
            name='Num_Emplois',
        ),
        migrations.AlterField(
            model_name='emplois_du_temps',
            name='Jour_Emplois',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
