# Generated by Django 4.2.2 on 2023-06-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_rename_horaire_matière_emplois_emplois_du_temps_horaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplois_du_temps',
            name='Num_Emplois',
            field=models.SmallAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emplois_du_temps',
            name='Jour_Emplois',
            field=models.CharField(max_length=30),
        ),
    ]
