# Generated by Django 4.2.2 on 2023-06-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_emplois_du_temps_num_emplois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois_du_temps',
            name='Num_Emplois',
        ),
        migrations.AddField(
            model_name='emplois_du_temps',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
