# Generated by Django 4.2.2 on 2023-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_remove_emplois_du_temps_num_emplois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois_du_temps',
            name='id',
        ),
        migrations.AddField(
            model_name='emplois_du_temps',
            name='Num_Emplois',
            field=models.PositiveIntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
