# Generated by Django 4.2.2 on 2023-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_remove_emplois_du_temps_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois_du_temps',
            name='Num_Emplois',
        ),
        migrations.AlterField(
            model_name='emplois_du_temps',
            name='Jour_Emplois',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
