# Generated by Django 4.2.2 on 2023-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0008_emplois_du_temps_num_emplois_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois_du_temps2',
            fields=[
                ('Num_Emplois', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Jour_Emplois', models.CharField(max_length=30)),
                ('Num_groupe', models.PositiveIntegerField()),
                ('Salle', models.CharField(max_length=30)),
                ('Semaine_Emplois', models.CharField(max_length=255)),
                ('Promotion_Emplois', models.CharField(max_length=255)),
                ('Matière', models.CharField(max_length=255)),
                ('Nom_professeur_Emplois', models.CharField(max_length=255)),
                ('début', models.TimeField()),
                ('fin', models.TimeField()),
                ('Horaire', models.PositiveIntegerField()),
                ('Temps', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Emplois du Temps',
                'verbose_name_plural': 'Emplois du Temps',
            },
        ),
        migrations.CreateModel(
            name='Emplois_du_temps3',
            fields=[
                ('Num_Emplois', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Jour_Emplois', models.CharField(max_length=30)),
                ('Num_groupe', models.PositiveIntegerField()),
                ('Salle', models.CharField(max_length=30)),
                ('Semaine_Emplois', models.CharField(max_length=255)),
                ('Promotion_Emplois', models.CharField(max_length=255)),
                ('Matière', models.CharField(max_length=255)),
                ('Nom_professeur_Emplois', models.CharField(max_length=255)),
                ('début', models.TimeField()),
                ('fin', models.TimeField()),
                ('Horaire', models.PositiveIntegerField()),
                ('Temps', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Emplois du Temps',
                'verbose_name_plural': 'Emplois du Temps',
            },
        ),
        migrations.RenameModel(
            old_name='Emplois_du_temps',
            new_name='Emplois_du_temps1',
        ),
    ]
