# Generated by Django 4.2.2 on 2023-06-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_emplois_du_temps2_emplois_du_temps3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplois_du_temps1',
            new_name='Emplois_du_temps',
        ),
        migrations.AlterModelOptions(
            name='emplois_du_temps',
            options={'verbose_name': 'Emplois du Temps1', 'verbose_name_plural': 'Emplois du Temps1'},
        ),
        migrations.AlterModelOptions(
            name='emplois_du_temps2',
            options={'verbose_name': 'Emplois du Temps2', 'verbose_name_plural': 'Emplois du Temps2'},
        ),
        migrations.AlterModelOptions(
            name='emplois_du_temps3',
            options={'verbose_name': 'Emplois du Temps3', 'verbose_name_plural': 'Emplois du Temps3'},
        ),
    ]
