# Generated by Django 4.2.2 on 2023-06-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0011_delete_emplois_du_temps2_delete_emplois_du_temps3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id_emploie', models.SmallAutoField(primary_key=True, serialize=False)),
                ('semaine', models.CharField(max_length=255)),
                ('promotion', models.CharField(max_length=255)),
                ('matière', models.CharField(max_length=255)),
                ('masse_horaire', models.PositiveIntegerField()),
                ('temps_restant', models.PositiveIntegerField()),
                ('professeur', models.CharField(max_length=255)),
                ('salle', models.CharField(max_length=30)),
                ('jour', models.CharField(max_length=30)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Emplois',
                'verbose_name_plural': 'Emplois',
            },
        ),
        migrations.DeleteModel(
            name='Emplois_du_temps',
        ),
    ]
