# Generated by Django 4.2.2 on 2023-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='création_emploie_du_temps',
            fields=[
                ('Num_Emplois', models.AutoField(primary_key=True, serialize=False)),
                ('Promotion_Emplois', models.CharField(max_length=255)),
                ('Libellé_Mat', models.CharField(max_length=255)),
                ('Horaire_Mat', models.IntegerField()),
                ('Temps_restant_Mat', models.IntegerField()),
                ('Nom_professeur', models.CharField(max_length=255)),
                ('Prénom_Professeur', models.CharField(max_length=255)),
                ('Date_cours', models.DateField()),
                ('Début_cours', models.TimeField()),
                ('Fin_cours', models.TimeField()),
                ('Bat_cours', models.CharField(default=None, max_length=255)),
                ('Sall_cours', models.CharField(default=None, max_length=255)),
                ('Date_exam', models.DateField(default=None)),
                ('Début_exam', models.TimeField(default=None)),
                ('Fin_exam', models.TimeField(default=None)),
            ],
            options={
                'verbose_name': 'création-emploie_du_temps',
                'verbose_name_plural': 'création-emploie_du_temps',
            },
        ),
    ]
