# Generated by Django 4.2.2 on 2023-06-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_emploi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='création_emploie_du_temps',
            name='Bat_cours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='création_emploie_du_temps',
            name='Date_exam',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='création_emploie_du_temps',
            name='Début_exam',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='création_emploie_du_temps',
            name='Fin_exam',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='création_emploie_du_temps',
            name='Sall_cours',
            field=models.CharField(max_length=255),
        ),
    ]
