# Generated by Django 4.2.2 on 2023-06-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_emploi', '0002_alter_création_emploie_du_temps_bat_cours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='création_emploie_du_temps',
            old_name='Sall_cours',
            new_name='Salle_cours',
        ),
    ]
